name: Message for First Time Issues

on: issues

jobs:
  greeting:
    runs-on: [ubuntu-18.04]
    steps:
    - name: Send message to the user
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Looks like this is your first issue on this repository. Please, fill the template completely to receive a quicker response from the staff members.\n\nThanks for playing on The Tofu Shop!"
